language: "python"

python:
    - "3.7"
    - "3.8"
    - "3.9-dev"
    - "pypy3"

install:
    - "pip install ."
    - "pip install -U coveralls flake8 sphinx sphinx_rtd_theme mypy numpy scipy"

script:
    - 'flake8 petbox/dca'
    - "mypy petbox/dca"
    - "pytest --cov=petbox.dca --cov-report=html -v test"
    - "sphinx-build -W -b html docs docs/_build/html"
    - "then mypy petbox/dca"

notifications:
    - email: false

after_success:
    - "coveralls"
