dist: "bionic"

language: "python"

python:
    - "3.8"
    - "3.9"
    - "3.10"

install:
    - "pip install -U \"flake8>=3.9.2\" \"mypy==0.910\" \"numpy>=1.21.1\" \"scipy>=1.7.1\" \"pytest>=6.2.4\" \"pytest-cov>=2.12.1\" \"attrs>=19.2.0\" \"hypothesis>=6.14.8\" \"coveralls>=3.2.0\" \"sphinx>=4.1.2\" \"sphinx_rtd_theme>=1.0.0\""
    - "pip install ."

script:
    - "flake8 petbox/dca"
    - "mypy petbox/dca"
    - "pytest"
    - "sphinx-build -W -b html docs docs/_build/html"

notifications:
    - email: false

after_success:
    - "coveralls"
